// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxVg213R7L9puEGn78v_7JFOt7SlImpLM',
    appId: '1:1056500006474:web:0fc9b1b851b7f97eabb0b3',
    messagingSenderId: '1056500006474',
    projectId: 'ask-mufti-30221',
    authDomain: 'ask-mufti-30221.firebaseapp.com',
    storageBucket: 'ask-mufti-30221.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJxDqjnqtWfqcUwCcndOlqDhzQG8d1klQ',
    appId: '1:1056500006474:android:02e198fe34e2e370abb0b3',
    messagingSenderId: '1056500006474',
    projectId: 'ask-mufti-30221',
    storageBucket: 'ask-mufti-30221.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2_cQRMzGaZBvgXtc8Xczb-HgNRmM-vAQ',
    appId: '1:1056500006474:ios:fdedc13752186542abb0b3',
    messagingSenderId: '1056500006474',
    projectId: 'ask-mufti-30221',
    storageBucket: 'ask-mufti-30221.firebasestorage.app',
    iosBundleId: 'com.example.askTheMufti',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC2_cQRMzGaZBvgXtc8Xczb-HgNRmM-vAQ',
    appId: '1:1056500006474:ios:fdedc13752186542abb0b3',
    messagingSenderId: '1056500006474',
    projectId: 'ask-mufti-30221',
    storageBucket: 'ask-mufti-30221.firebasestorage.app',
    iosBundleId: 'com.example.askTheMufti',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDxVg213R7L9puEGn78v_7JFOt7SlImpLM',
    appId: '1:1056500006474:web:c72e432f930e85ecabb0b3',
    messagingSenderId: '1056500006474',
    projectId: 'ask-mufti-30221',
    authDomain: 'ask-mufti-30221.firebaseapp.com',
    storageBucket: 'ask-mufti-30221.firebasestorage.app',
  );
}
